### ISSUE TITLE
Model answer edge and node IDs are different from initial state IDs

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#113]
Low priority issue. The root of the problem is that JSAV creates different objects for exercise instance and model answer. We would need a mapping function from model answer objects to exercise instance objects, and that is not trivial.

Fixing this issue would allow automatic comparison of the student's answer to the model answer in the JAAL recording. However, we don't have a use case for that.

**Comment by Meratyn** [comment]
Mapping the model answer object to the exercise instance object requires making assumptions about the content of the objects to do it in an efficient manner. As such, if one wishes to compare the objects 1-to-1 rather than merely running the svg images in the JSAV player, this mapping should be made in the data analysis with knowledge about what assumptions can be made.
