### ISSUE TITLE
Remove after Undo causes TypeError

### ISSUE THREAD

**Issue by atilante** [Aalto-LeTech/jsav-exercise-recorder#66]
- Enqueue an edge, click Undo, click Remove
  -> TypeError: edge is undefined in DijkstraPE-research-v2.js:1351

**Comment by Meratyn** [comment]
Resolved in #55 : the error occurred because heapsize was a local variable, which meant that it did not revert to the previous value when an undo step was done. 
Changing heapsize to a JSAV variable resolved this, as now JSAV keeps track of its value and sets it to the correct one when a step is undone.
